user/urls.py
from django.urls import path

from user.views import (
    index,
    UserListView,
    UserCreateView,
    GroupListView,
    GroupCreateView,
    UserUpdateView,
    UserDeleteView,
    GroupUpdateView,
    GroupDeleteView
)


urlpatterns = [
    path("", index, name="index"),
    path("users/", UserListView.as_view(), name="user-list"),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="user-update"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("groups/", GroupListView.as_view(), name="group-list"),
    path("group/create/", GroupCreateView.as_view(), name="group-create"),
    path("group/<int:pk>/update/", GroupUpdateView.as_view(), name="group-update"),
    path("group/<int:pk>/delete/", GroupDeleteView.as_view(), name="group-delete"),
]

app_name = "user"

user_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls", namespace="user"))
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField()

    def __str__(self) -> str:
        return self.name


class User(AbstractUser):
    groups = models.ManyToManyField(to=Group, related_name="users", blank=True)

    def __str__(self) -> str:
        return self.username

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from user.models import User, Group


class UsersCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password1", "password2", "groups")


class UsersUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "groups")


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from user.forms import UsersCreationForm, GroupForm, UsersUpdateForm
from user.models import User, Group


def index(request):

    return render(request, "index.html")


class UserListView(generic.ListView):
    model = User
    queryset = User.objects.prefetch_related("groups")
    paginate_by = 5


class UserCreateView(generic.CreateView):
    model = User
    form_class = UsersCreationForm
    success_url = reverse_lazy("user:user-list")


class UserUpdateView(generic.UpdateView):
    model = User
    form_class = UsersUpdateForm
    success_url = reverse_lazy("user:user-list")


class UserDeleteView(generic.DeleteView):
    model = User
    success_url = reverse_lazy("user:user-list")


class GroupListView(generic.ListView):
    model = Group
    queryset = Group.objects.prefetch_related("users")
    paginate_by = 5


class GroupCreateView(generic.CreateView):
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy("user:group-list")


class GroupUpdateView(generic.UpdateView):
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy("user:group-list")


class GroupDeleteView(generic.DeleteView):
    model = Group
    success_url = reverse_lazy("user:group-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Test Task</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
  {% block navbar %}
    {% include "includes/navbar.html" %}
  {% endblock %}
  <div class="row justify-content-center">
    <div class="col-sm-10">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "user:user-list" %}">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "user:group-list" %}">Groups</a>
      </li>
    </ul>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>This test task is completed by Taras Borshch</h1>
  <p>Here is the link to my GitHub</p>
  <a href="https://github.com/Barsh4ec/" class="btn btn-outline-success ml-auto">
    GitHub
  </a>

{% endblock %}

templates/user/group_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Group?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <a  href="{% url "user:group-list" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/user/group_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create Group</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/user/group_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex">
    <h3 class="mr-auto mt-4">Groups</h3>
    <a href="{% url "user:group-create" %}" class="btn btn-outline-primary ml-auto mt-4 mr-5">
      Create Group
    </a>
  </div>
  <br>
  {% if group_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Group members</th>
        <th>Actions</th>
      </tr>
      {% for group in group_list %}
        <tr>
          <td>{{ group.id }}</td>
          <td>{{ group.name }}</td>
          <td>{{ group.description }}</td>
          <td>
            {% for user in group.users.all %}
              {{ user }},
            {% endfor %}
          </td>
          <td>
            <a href="{% url "user:group-update" pk=group.id %}" class="btn btn-secondary link-to-page">
              Update
            </a>
            {% if group.users.count == 0 %}
              <a href="{% url "user:group-delete" pk=group.id %}" class="btn btn-danger link-to-page">
                Delete
              </a>
            {% endif %}
          </td>

        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no groups yet.</p>
  {% endif %}
{% endblock %}

templates/user/user_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete User?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <a  href="{% url "user:user-list" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/user/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create User</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/user/user_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex">
    <h3 class="mr-auto mt-4">Users</h3>
    <a href="{% url "user:user-create" %}" class="btn btn-outline-primary ml-auto mt-4 mr-5">
      Add User
    </a>
  </div>
  <br>
  {% if user_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Created</th>
        <th>Groups</th>
        <th>Actions</th>
      </tr>
      {% for user in user_list %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.username }} {% if user == driver %} (Me){% endif %}</td>
          <td>{{ user.date_joined }}</td>
          <td>
            {% for group in user.groups.all %}
              {{ group }},
            {% endfor %}
          </td>
          <td>
            <a href="{% url "user:user-update" pk=user.id %}" class="btn btn-secondary link-to-page">
              Update
            </a>
            <a href="{% url "user:user-delete" pk=user.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
          </td>

        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no users yet.</p>
  {% endif %}
{% endblock %}